#!/usr/bin/env node
const term = require( 'terminal-kit' ).terminal
const xray = require('x-ray')
const open = require('open')
const x = xray()

const params = process.argv.slice(2)
if (params.length === 0) {
  term.cyan('o [query]')
  term.yellow(`

    Example
      o elon musk

  `)
  
  return
}

x(`https://www.google.com/search?q=${process.argv.slice(2).join('+')}`, 'a', [{
  title: 'h3',
  link: '@href'
}])((err, results) => {
  if (err) {
    throw err
  }
  const items = results.filter(v => v.title).map(v => {
    const idx = v.link.indexOf('=https');
    const parsed = v.link.substring(idx + 1)
    const readyLink = parsed.split('&')[0]
    return ({
      title: v.title,
      link: readyLink
    })
  })
  term.singleColumnMenu(items.map(v => v.title), function(error, response) {
      open(items[response.selectedIndex].link)
      process.exit();
  });
})
